authors = ["PepeElToro41"]
description = "Utilities for UI Labs, a storybook-like plugin for roblox"
includes = [
    "pesde.toml",
    "README.md",
    "LICENSE.md",
    "src",
]
license = "MIT"
name = "pepeeltoro41/ui_labs"
repository = "https://github.com/PepeElToro41/ui-labs"
version = "2.3.8"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[target]
build_files = ["src"]
environment = "roblox"
lib = "src/init.luau"
