[package]
name = "pepeeltoro41/ui-labs"
description = "Utilities for UI Labs, a storybook-like plugin for roblox"
license = "MIT"
version = "2.3.2"
authors = ["PepeElToro41"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**", "src/*.ts"]
include = [
    "src",
    "src/**",
    "default.project.json",
    "wally.toml",
    "wally.lock",
    "LICENSE.md",
    "README.md",
]
